# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nick_name', models.CharField(blank=True, max_length=256, verbose_name='\u6635\u79f0')),
                ('status', models.IntegerField(choices=[(1, '\u6ce8\u518c\u4e2d'), (5, '\u5f85\u5ba1\u6838'), (11, '\u6b63\u5e38'), (21, '\u4f11\u606f\u4e2d'), (99, '\u5df2\u7981\u7528')], default=1, verbose_name='\u72b6\u6001')),
                ('phone', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('is_staff', models.BooleanField(default=False, verbose_name='\u7cfb\u7edf\u7ba1\u7406\u5458')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8d26\u53f7\u7cfb\u7edf',
                'verbose_name_plural': '\u7528\u6237\u8d26\u53f7\u7cfb\u7edf',
            },
        ),
    ]
